<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Version>1.0.4</Version>
    <Authors>Ollie Day</Authors>
    <Title>Daffer</Title>
    <Description>Functional wrapper for Dapper.</Description>
    <Copyright>Copyright 2018, 2022, 2025 (c) Ollie Day</Copyright>
    <PackageTags>F#;Dapper;SQL</PackageTags>
    <PackageLicenseUrl>https://github.com/OllieDay/Daffer/blob/master/LICENSE</PackageLicenseUrl>
    <PackageProjectUrl>https://github.com/OllieDay/Daffer</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Daffer.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
  </ItemGroup>

</Project>
